#! python3
"""Colors a sequence with provided color."""

from pymol import cmd


NIFB = """
MELSVLGQNNGGQHSAGGCSSSSCGSTHDQLSHLPENIRAKVQNHPCYSEEAHHYFARM
HVAVAPACNIQCHYCNRKYDCANESRPGVVSEVLTPEQAVKKVKAVAAAIPQMSVLGIA
GPGDPLANPKRTLDTFRMLSEQAPDIKLCVSTNGLALPECVEELAKHNIDHVTITINCV
DPEIGAKIYPWIYWNNKRIRGVKAAKILIEQQQKGLEMLVARGILVKVNSVMIPGVNDE
HLKEVSKIVKAKGAFLHNVMPLIAEPEHGTFYGVMGQRSPEPEELQDLQDACAGDMNMM
RHCRQCRADAVGMLGEDRGDEFTLDKIESMEIDYEAAMVKRAAIHAAIKEELDEKAAKK
ERLAGLSVASVQNGTSGRYRPVLMAVATSGGGLINQHFGHATEFLVYEASPSGVRFIGH
RRVDQYCVGNDTCGEKESALAGSIRALKGCEAVLCSKIGFEPWSDLETAGIQPNGEHAM
EPIEEAVMAVYREMIESGRLENDGALLQAKA
"""
NIFBX = """
MEIDYEAAMVKRAAIHAAIKEELDEKAAKKERLAGLSVASVQNGTSGRYRPVLMAVATS
GGGLINQHFGHATEFLVYEASPSGVRFIGHRRVDQYCVGNDTCGEKESALAGSIRALKG
CEAVLCSKIGFEPWSDLETAGIQPNGEHAMEPIEEAVMAVYREMIESGRLENDGAL
LQAKA
"""
NIFBDELTABX = """
MELSVLGQNNGGQHSAGGCSSSSCGSTHDQLSHLPENIRAKVQNHPCYSEEAHHYFARM
HVAVAPACNIQCHYCNRKYDCANESRPGVVSEVLTPEQAVKKVKAVAAAIPQMSVLGIA
GPGDPLANPKRTLDTFRMLSEQAPDIKLCVSTNGLALPECVEELAKHNIDHVTITINCV
DPEIGAKIYPWIYWNNKRIRGVKAAKILIEQQQKGLEMLVARGILVKVNSVMIPGVNDE
HLKEVSKIVKAKGAFLHNVMPLIAEPEHGTFYGVMGQRSPEPEELQDLQDACAGDMNMM
RHCRQCRADAVGMLGEDRGDEFTLDKIES
"""
NAFV = """
MALKIVESCVNCWACVDVCPSEAISLAGPHFEISASKCTECDGDYAEKQCASICPVEGA
ILLADGTPANPPGSLTGIPPERLAEAMREIQAR
"""
NAFF = """
MITLTESAKSAVTRFISSTGKPIAGLRIRVEGGGCSGLKYSLKLEEAGAEDDQLVDCDG
ITLLIDSASAPLLDGVTMDFVESMEGSGFTFVNPNATNSCGCGKSFAC
"""

SEQUENCES = {
    "nifb": (NIFB, "bluewhite"),
    "nifbx": (NIFBX, "limegreen"),
    "nifbdeltabx": (NIFBDELTABX, "deepteal"),
    "nafv": (NAFV, "firebrick"),
    "naff": (NAFF, "deeppurple"),
}


@cmd.extend
def color_seq(sequence: str, color: str, temp_name: str = "tmp_color") -> None:
    """Colors sequence with color."""
    cmd.select(temp_name, f"elem C & pepseq {sequence}")
    cmd.color(color, temp_name)


@cmd.extend
def color_prot(name: str, color: str = "") -> None:
    """Colors known protein with color."""
    name = name.lower()
    sequence = SEQUENCES[name][0]
    colour = color or SEQUENCES[name][1]
    color_seq(sequence, colour)


@cmd.extend
def color_prots() -> None:
    """Colors known sequences with default colors."""
    for protein in SEQUENCES:
        color_prot(protein)


if __name__ == "__main__":
    color_prots()
